/**
 * BlackRoad Worlds Feed Worker
 * Serves world artifacts from BlackRoad-OS-Inc/blackroad-agents
 * Routes:
 *   GET /        → JSON feed
 *   GET /rss     → RSS 2.0 feed
 *   GET /atom    → Atom 1.0 feed
 *   GET /<id>    → Single world artifact
 */

const REPO = "BlackRoad-OS-Inc/blackroad-agents"
const GITHUB_API = "https://api.github.com"
const CACHE_TTL = 120 // 2 minutes

function parseWorldPath(path) {
  const m = path.match(/^([\w-]+)\/((\d{8})_(\d{6})_(world|lore|code)_(.+))\.md$/)
  if (!m) return null
  const [, dir, filename, date, time, type, slug] = m
  const node = dir === "worlds" ? "aria64" : dir.replace("-worlds", "")
  const ts = `${date.slice(0,4)}-${date.slice(4,6)}-${date.slice(6,8)}T${time.slice(0,2)}:${time.slice(2,4)}:${time.slice(4,6)}Z`
  return {
    id: filename,
    title: slug.replace(/-/g, " ").replace(/\b\w/g, c => c.toUpperCase()),
    node, type, path, timestamp: ts,
    link: `https://github.com/${REPO}/blob/main/${path}`,
  }
}

async function fetchWorlds(env) {
  const token = env.GITHUB_TOKEN
  const headers = { Accept: "application/vnd.github.v3+json" }
  if (token) headers.Authorization = `Bearer ${token}`

  const res = await fetch(`${GITHUB_API}/repos/${REPO}/git/trees/main?recursive=1`, { headers })
  if (!res.ok) throw new Error(`GitHub ${res.status}`)
  const tree = await res.json()

  return tree.tree
    .map(f => f.path)
    .filter(p => (p.startsWith("worlds/") || p.includes("-worlds/")) && p.endsWith(".md"))
    .map(parseWorldPath)
    .filter(Boolean)
    .sort((a, b) => b.timestamp.localeCompare(a.timestamp))
}

async function fetchWorldContent(path, env) {
  const token = env.GITHUB_TOKEN
  const headers = { Accept: "application/vnd.github.v3+json" }
  if (token) headers.Authorization = `Bearer ${token}`
  const res = await fetch(`${GITHUB_API}/repos/${REPO}/contents/${path}`, { headers })
  if (!res.ok) return null
  const data = await res.json()
  return atob(data.content.replace(/\n/g, ""))
}

function rss(worlds) {
  const items = worlds.slice(0, 50).map(w => `
    <item>
      <title>${w.title} [${w.type}@${w.node}]</title>
      <link>${w.link}</link>
      <guid>${w.id}</guid>
      <pubDate>${new Date(w.timestamp).toUTCString()}</pubDate>
      <description><![CDATA[World artifact generated by ${w.node} node — type: ${w.type}]]></description>
      <category>${w.type}</category>
      <author>${w.node}@blackroad.ai</author>
    </item>`).join("")

  return `<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>BlackRoad Worlds</title>
    <link>https://worlds.blackroad.io</link>
    <description>AI-generated world artifacts from autonomous Pi nodes</description>
    <language>en-us</language>
    <lastBuildDate>${new Date().toUTCString()}</lastBuildDate>
    <atom:link href="https://worlds.blackroad.io/rss" rel="self" type="application/rss+xml"/>
    ${items}
  </channel>
</rss>`
}

function atom(worlds) {
  const entries = worlds.slice(0, 50).map(w => `
  <entry>
    <id>urn:blackroad:world:${w.id}</id>
    <title>${w.title}</title>
    <link href="${w.link}"/>
    <updated>${w.timestamp}</updated>
    <author><name>${w.node}</name><email>${w.node}@blackroad.ai</email></author>
    <category term="${w.type}"/>
    <summary>World artifact — ${w.type} from @${w.node}</summary>
  </entry>`).join("")

  return `<?xml version="1.0" encoding="UTF-8"?>
<feed xmlns="http://www.w3.org/2005/Atom">
  <id>https://worlds.blackroad.io/atom</id>
  <title>BlackRoad Worlds</title>
  <link href="https://worlds.blackroad.io"/>
  <link rel="self" href="https://worlds.blackroad.io/atom"/>
  <updated>${new Date().toISOString()}</updated>
  <author><name>BlackRoad OS</name></author>
  ${entries}
</feed>`
}

export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url)
    const path = url.pathname.replace(/^\//, "")
    const cache = caches.default
    const cacheKey = new Request(request.url, request)

    // Check cache
    const cached = await cache.match(cacheKey)
    if (cached) return cached

    try {
      if (!path || path === "json") {
        const worlds = await fetchWorlds(env)
        const body = JSON.stringify({
          total: worlds.length,
          nodes: {
            aria64: worlds.filter(w => w.node === "aria64").length,
            alice: worlds.filter(w => w.node === "alice").length,
          },
          worlds: worlds.slice(0, 50),
        }, null, 2)
        const res = new Response(body, {
          headers: {
            "Content-Type": "application/json",
            "Cache-Control": `public, max-age=${CACHE_TTL}`,
            "Access-Control-Allow-Origin": "*",
          }
        })
        ctx.waitUntil(cache.put(cacheKey, res.clone()))
        return res
      }

      if (path === "rss") {
        const worlds = await fetchWorlds(env)
        const res = new Response(rss(worlds), {
          headers: {
            "Content-Type": "application/rss+xml; charset=utf-8",
            "Cache-Control": `public, max-age=${CACHE_TTL}`,
          }
        })
        ctx.waitUntil(cache.put(cacheKey, res.clone()))
        return res
      }

      if (path === "atom") {
        const worlds = await fetchWorlds(env)
        const res = new Response(atom(worlds), {
          headers: {
            "Content-Type": "application/atom+xml; charset=utf-8",
            "Cache-Control": `public, max-age=${CACHE_TTL}`,
          }
        })
        ctx.waitUntil(cache.put(cacheKey, res.clone()))
        return res
      }

      // Single world: /20260223_040142_world_world-24
      const worlds = await fetchWorlds(env)
      const world = worlds.find(w => w.id === path)
      if (world) {
        const content = await fetchWorldContent(world.path, env)
        const res = new Response(JSON.stringify({ ...world, content }), {
          headers: {
            "Content-Type": "application/json",
            "Cache-Control": `public, max-age=3600`,
            "Access-Control-Allow-Origin": "*",
          }
        })
        ctx.waitUntil(cache.put(cacheKey, res.clone()))
        return res
      }

      return new Response("Not found", { status: 404 })
    } catch (err) {
      return new Response(JSON.stringify({ error: err.message }), {
        status: 500,
        headers: { "Content-Type": "application/json" }
      })
    }
  }
}