name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Worker
    steps:
      - uses: actions/checkout@v4
      - name: Deploy with Wrangler
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: "848cf0b18d51e0170e0d1537aec3505a"
          secrets: |
            GITHUB_TOKEN
        env:
          GITHUB_TOKEN: ${{ secrets.BLACKROAD_GITHUB_TOKEN }}
